### ISSUE TITLE
style: Dar destaque ao link que redireciona no repositório  

### ISSUE THREAD

**Issue by Afranioalves** [angolaosc/aosc.social#10]
777- Seria muito legal, se os usuários pudessem identificar textos clicáveis (links) e não clicáveis.
Eu inclusive, tive dificuldades , pois onde o link que redireciona ao repositório está, não dá para perceber se é  clicavel ou não, está no rodapé, juntamente com a informação do copyright, sem nenhum destaque visível, fazendo-lhe parecer como se fosse apenas um simples texto, passando uma informação...

**Comment by antonio-pedro99** [comment]
Obrigado pela PR @Afranioalves 

O que tens a dizer @Danguya ??

**Comment by Danguya** [comment]
**Achei interessante, vou dar um jeito neste quesito.**

**Comment by Danguya** [comment]
Resolvido

**Comment by antonio-pedro99** [comment]
@Danguya acho que deve marcar como resolvido quando a PR estiver pronta.
Enquanto isso pode deixar aberto. 

ATT: Não esqueça mencionar que a PR resolve essa issue. Alguma coisa na descrição da PR como "Resolve #10"
