### ISSUE TITLE
style: Aplicar anti-deformação nas imagem do core team

### ISSUE THREAD

**Issue by Afranioalves** [angolaosc/aosc.social#11]
777- As imagens dos membros do core team, estão distorcida, seria legal se os usuários, pudessem enxergar corretamente as imagens, na sua perspectiva real.    

![Imagem Distorcida](https://raw.githubusercontent.com/Afranioalves/ATM/main/avatar.PNG)

**Comment by antonio-pedro99** [comment]
Você quer trabalhar nessa issue? @Afranioalves ?

**Comment by Afranioalves** [comment]
777- yha, can I ?

**Comment by antonio-pedro99** [comment]
É open-source, mas deixa ver se o @Danguya já está a trabalhar nisso.

**Comment by Afranioalves** [comment]
777- Eu já fiz 😁😁

**Comment by antonio-pedro99** [comment]
closed by #13
