### ISSUE TITLE
mudar o icon do site

### ISSUE THREAD

**Issue by antonio-pedro99** [angolaosc/aosc.social#18]
Parece que o site está usando  o icon da vercel.

**Comment by antonio-pedro99** [comment]
@Danguya ainda vejo o icon da vercel.

**Comment by Danguya** [comment]
@antonio-pedro99  Eu já havia resolvido a bastante tempo, verifique aqui https://aosc-social-git-feat-add-favicon-angola-open-source-community.vercel.app/

**Comment by antonio-pedro99** [comment]
Então acontece que vc fechou a PR e năo mesclou.
