### ISSUE TITLE
Feat: Adicionar botão flutuante pra aba de histórico de evento e uma versão do site em inglês.

### ISSUE THREAD

**Issue by elisioMassaqui** [angolaosc/aosc.social#29]
Seria muito bom ter um botão flutuante no lado direito ou esquerdo e a uma posição do meio da tela que leva pra uma aba de histórico de atividades e eventos apresentados de uma forma breve de modo a trazer mais curiosidade e motivação por parte de quem teve o primeiro contacto, o botão pode ter uma animação de rotação ou uma luz feito com css pra chamar atenção, porque pode haver pessoas que irão se interessar mais só pela emoção e empolgação apresentados na aba de histórico e evento da equipe e comunidade, mas não é necessário que tenha muita informação como já disse.

E também seria ótimo site ter uma versão em inglês e com a opção de alterar idioma no site mesmo, pra alcançar um público mais amplo.

![Screenshot_20231012-160530](https://github.com/angolaosc/aosc.social/assets/145590545/a853e866-1056-456d-836b-836d80d10176)

**Comment by elisioMassaqui** [comment]
@antonio-pedro99 

quero criar uma nova page ( de historico da comunidade breve info do que já aconteceu pra o user ficar mais interresado) que vai aparecer quando o user clicar no botão flutuante.

**Comment by antonio-pedro99** [comment]
> @antonio-pedro99
> 
> quero criar uma nova page ( de historico da comunidade breve info do que já aconteceu pra o user ficar mais interresado) que vai aparecer quando o user clicar no botão flutuante.

Para ser franco, nós não precisamos disso agora. 

Que tal você dar uma olhada nessas issues? 
https://github.com/DesignLiquido/delegua/labels/good%20first%20issue

**Comment by elisioMassaqui** [comment]
@antonio-pedro99 então a minha equipe pode contribuir numa issue de outro project , desde que ninguem esteja trabalhando nela?

**Comment by antonio-pedro99** [comment]
> @antonio-pedro99 então a minha equipe pode contribuir numa issue de outro project , desde que ninguem esteja trabalhando nela?

Exatamente!
