### ISSUE TITLE
Efeito de digitação no texto do card nossas motivações.

### ISSUE THREAD

**Issue by elisioMassaqui** [angolaosc/aosc.social#38]

**Comment by Francisco-dos-Santos** [comment]
Estou disponível para trabalhar nesse problema

**Comment by antonio-pedro99** [comment]
Esse problema precisa de triagem!
@elisioMassaqui  é difícil saber sobre o que é essa funcionalidade sem nenhuma demostração.

**Comment by elisioMassaqui** [comment]
Que tipo de demonstração @antonio-pedro99 
Eu já fiz e mandei, só não sei se foi mesclado.
