### ISSUE TITLE
remover header sobre Angola Open-source Fest

### ISSUE THREAD

**Issue by antonio-pedro99** [angolaosc/aosc.social#64]
Agora que o AOSFest terminou, seria legal remover esse header?
![image](https://github.com/angolaosc/aosc.social/assets/42675180/bf2802f9-33e3-47ff-a205-262af50f1fa3)

**Comment by sukuasoft** [comment]
Fiz um PR para esta issue. [aqui]( https://github.com/angolaosc/aosc.social/pull/65)
