### ISSUE TITLE
Google Summer of Code 2024: Bolsas de Estágio Remunerado do Google

### ISSUE THREAD

**Issue by antonio-pedro99** [angolaosc/aosc.social#73]
Ola @euotiniel @CristinoCg seria legal a gente escrever um blog sobre o Google Summer of Code? As inscrições irão abrir já no dia 18 e seria legal partilhar com a comunidade.

### O que incluir no Blog?

Aqui estão algumas sugestões sobre o que podemos incluir:

1. **Introdução ao Google Summer of Code (GSoC)**:
   - Explicação sobre o que é o GSoC, seu histórico(com métricas) e objetivo.
   - Detalhes sobre como o programa funciona, incluindo o processo de inscrição, seleção de projetos e estudantes, cronograma, etc.

2. **Informações sobre o GSoC 2024**:
   - Destaques das novidades e mudanças na edição de 2024.
   - Data de inscrição, prazos importantes e cronograma geral.

3. **Guias e Dicas para Participantes**:
   - Orientações sobre como selecionar projetos e organizar a sua inscrição.
   - Dicas para redigir uma proposta de projeto forte e convincente.
   - Estratégias para se destacar durante o período de aplicação e seleção.

4. **Recursos e Ferramentas Úteis**:
   - Listas de recursos, como tutoriais, documentação e ferramentas de desenvolvimento.
   - Informações sobre comunidades e fóruns de discussão onde os participantes podem obter suporte e colaboração.

5. **Atualizações e Notícias do GSoC 2024**:
Aqui podemos informar que os interessados podem usar o canal #google-summer-of-code lá no servidor da comunidade para se manter actualizado.

6. **Conselhos de Mentores e Organizadores**:
Neste ponto podemos mencionar sobre o episódio do podcast que teremos na próxima quarta-feira, encontre mais detalhes nas nossas redes sociais ou Youtube.

Podemos remover ou adicionar mais detalhes, me diz o que acha!

### Recursos: 
**Site oficial**: https://summerofcode.withgoogle.com/
**Programa de 2024**: https://opensource.googleblog.com/2024/02/mentor-organizations-announced-for-google-summer-of-code-2024.html
**Guia de Contribuição**: https://google.github.io/gsocguides/student
**Timeline**: https://developers.google.com/open-source/gsoc/timeline

**Comment by euotiniel** [comment]
Boa! @antonio-pedro99 vi o "índice" que sugeriste e hoje me deixei levar pelos vários artigos que o Google havia postado, além, claro, das referências que deixaste.

Tem muitas ideias bem interessantes, mas enfim, pensei em fazer esse artigo por partes. Acho que falar sobre tudo o que seria necessário em um único artigo causaria uma overdose, além de deixar o artigo muito longo. Então, poderíamos escrever o primeiro artigo falando sobre: **o que é, como participar, pq...**, e o segundo poderia ser mais "prático" com: **dicas da inscrição, aprofundar mais os processos e talvez testemunhos para dar aquela empolgada** (poderia ser postado alguns dias antes da abertura das inscrições).

Então, para o primeiro artigo, caso seja aprovado, poderíamos ter:

### Introdução

- O que é o GSoC?
- História e origens do Google Summer of Code
- Objetivos do programa
- Impacto na comunidade de código aberto

### Vantagens de Participar

- Benefícios para os estudantes
- Destaques das novidades e mudanças na edição de 2024

### Processo de Inscrição

- Como se inscrever no Google Summer of Code
- Critérios de seleção e avaliação de propostas de projetos

### Empresas e Mentores em 2024

- Lista de algumas das 850 empresas colaboradoras
- Visão geral dos mais de 19 mil mentores disponíveis
- Papel dos mentores no programa

### Dicas e Recursos

- Artigos, vídeos e tutoriais úteis para os participantes
- Informações sobre comunidades e fóruns de discussão
- Como a Angola Open Source Community pode ajudar
- Utilização do canal da Angola Open Source Community

### Conclusão

**Comment by antonio-pedro99** [comment]
> Boa! @antonio-pedro99 vi o "índice" que sugeriste e hoje me deixei levar pelos vários artigos que o Google havia postado, além, claro, das referências que deixaste.
> 
> Tem muitas ideias bem interessantes, mas enfim, pensei em fazer esse artigo por partes. Acho que falar sobre tudo o que seria necessário em um único artigo causaria uma overdose, além de deixar o artigo muito longo. Então, poderíamos escrever o primeiro artigo falando sobre: **o que é, como participar, pq...**, e o segundo poderia ser mais "prático" com: **dicas da inscrição, aprofundar mais os processos e talvez testemunhos para dar aquela empolgada** (poderia ser postado alguns dias antes da abertura das inscrições).
> 
> Então, para o primeiro artigo, caso seja aprovado, poderíamos ter:
> 
> ### Introdução
> * O que é o GSoC?
> * História e origens do Google Summer of Code
> * Objetivos do programa
> * Impacto na comunidade de código aberto
> 
> ### Vantagens de Participar
> * Benefícios para os estudantes
> * Destaques das novidades e mudanças na edição de 2024
> 
> ### Processo de Inscrição
> * Como se inscrever no Google Summer of Code
> * Critérios de seleção e avaliação de propostas de projetos
> 
> ### Empresas e Mentores em 2024
> * Lista de algumas das 850 empresas colaboradoras
> * Visão geral dos mais de 19 mil mentores disponíveis
> * Papel dos mentores no programa
> 
> ### Dicas e Recursos
> * Artigos, vídeos e tutoriais úteis para os participantes
> * Informações sobre comunidades e fóruns de discussão
> * Como a Angola Open Source Community pode ajudar
> * Utilização do canal da Angola Open Source Community
> 
> ### Conclusão
 
 Ficou interessante. 
Seria legal informar que teremos um episódio do podcast com o LAPPIS(uma organização participando como mentor).
Acho que podemos começar!

**Comment by CristinoCg** [comment]
> > Boa! @antonio-pedro99 vi o "índice" que sugeriste e hoje me deixei levar pelos vários artigos que o Google havia postado, além, claro, das referências que deixaste.
> > 
> > Tem muitas ideias bem interessantes, mas enfim, pensei em fazer esse artigo por partes. Acho que falar sobre tudo o que seria necessário em um único artigo causaria uma overdose, além de deixar o artigo muito longo. Então, poderíamos escrever o primeiro artigo falando sobre: **o que é, como participar, pq...**, e o segundo poderia ser mais "prático" com: **dicas da inscrição, aprofundar mais os processos e talvez testemunhos para dar aquela empolgada** (poderia ser postado alguns dias antes da abertura das inscrições).
> > 
> > Então, para o primeiro artigo, caso seja aprovado, poderíamos ter:
> > 
> > ### Introdução
> > * O que é o GSoC?
> > * História e origens do Google Summer of Code
> > * Objetivos do programa
> > * Impacto na comunidade de código aberto
> > 
> > ### Vantagens de Participar
> > * Benefícios para os estudantes
> > * Destaques das novidades e mudanças na edição de 2024
> > 
> > ### Processo de Inscrição
> > * Como se inscrever no Google Summer of Code
> > * Critérios de seleção e avaliação de propostas de projetos
> > 
> > ### Empresas e Mentores em 2024
> > * Lista de algumas das 850 empresas colaboradoras
> > * Visão geral dos mais de 19 mil mentores disponíveis
> > * Papel dos mentores no programa
> > 
> > ### Dicas e Recursos
> > * Artigos, vídeos e tutoriais úteis para os participantes
> > * Informações sobre comunidades e fóruns de discussão
> > * Como a Angola Open Source Community pode ajudar
> > * Utilização do canal da Angola Open Source Community
> > 
> > ### Conclusão
>  
>  Ficou interessante. 
> Seria legal informar que teremos um episódio do podcast com o LAPPIS(uma organização participando como mentor).
> Acho que podemos começar!

Como é suposto contribuirmos no mesmo artigo? Tem já um workflow que usam ou é perguntando para quem já está a escrever?

**Comment by euotiniel** [comment]
@antonio-pedro99 é possível fornecer mais conteúdos sobre o processo de inscrição?

**Comment by antonio-pedro99** [comment]
> @antonio-pedro99 é possível fornecer mais conteúdos sobre o processo de inscrição?

https://www.freecodecamp.org/news/how-to-apply-to-google-summer-of-code/

**Comment by antonio-pedro99** [comment]
> > > Boa! @antonio-pedro99 vi o "índice" que sugeriste e hoje me deixei levar pelos vários artigos que o Google havia postado, além, claro, das referências que deixaste.
> > > Tem muitas ideias bem interessantes, mas enfim, pensei em fazer esse artigo por partes. Acho que falar sobre tudo o que seria necessário em um único artigo causaria uma overdose, além de deixar o artigo muito longo. Então, poderíamos escrever o primeiro artigo falando sobre: **o que é, como participar, pq...**, e o segundo poderia ser mais "prático" com: **dicas da inscrição, aprofundar mais os processos e talvez testemunhos para dar aquela empolgada** (poderia ser postado alguns dias antes da abertura das inscrições).
> > > Então, para o primeiro artigo, caso seja aprovado, poderíamos ter:
> > > ### Introdução
> > > 
> > > * O que é o GSoC?
> > > * História e origens do Google Summer of Code
> > > * Objetivos do programa
> > > * Impacto na comunidade de código aberto
> > > 
> > > ### Vantagens de Participar
> > > 
> > > * Benefícios para os estudantes
> > > * Destaques das novidades e mudanças na edição de 2024
> > > 
> > > ### Processo de Inscrição
> > > 
> > > * Como se inscrever no Google Summer of Code
> > > * Critérios de seleção e avaliação de propostas de projetos
> > > 
> > > ### Empresas e Mentores em 2024
> > > 
> > > * Lista de algumas das 850 empresas colaboradoras
> > > * Visão geral dos mais de 19 mil mentores disponíveis
> > > * Papel dos mentores no programa
> > > 
> > > ### Dicas e Recursos
> > > 
> > > * Artigos, vídeos e tutoriais úteis para os participantes
> > > * Informações sobre comunidades e fóruns de discussão
> > > * Como a Angola Open Source Community pode ajudar
> > > * Utilização do canal da Angola Open Source Community
> > > 
> > > ### Conclusão
> > 
> > 
> > Ficou interessante.
> > Seria legal informar que teremos um episódio do podcast com o LAPPIS(uma organização participando como mentor).
> > Acho que podemos começar!
> 
> Como é suposto contribuirmos no mesmo artigo? Tem já um workflow que usam ou é perguntando para quem já está a escrever?

O @euotiniel vai te explicar
