### ISSUE TITLE
refactor: remover espaços em branco a mais, alinhar espaçamentos e distâncias entre secções e demais componentes

### ISSUE THREAD

**Issue by trupakufi** [angolaosc/aosc.social#77]
## Descrição 

Este é um problema visual.

E o objectivo é remover mesmo os espaços que existem em branco, mas não todos porque alguns fazem parte do design, enquanto que outros parece que foram adicionados sem querer, isso para alinhar as secções e unificar o tamanho e a distância entre as secções e demais componentes

**Comment by euotiniel** [comment]
Podes especificar os onde encontrar? Com imagens se puder...

**Comment by antonio-pedro99** [comment]
> Podes especificar os onde encontrar? Com imagens se puder...

Acho que ele fala desse

![image](https://github.com/angolaosc/aosc.social/assets/42675180/6afd36f3-3d31-43b0-abfd-e6b1235e0008)

**Comment by euotiniel** [comment]
@antonio-pedro99 @trupakufi apenas aqui?

**Comment by trupakufi** [comment]
Apenas aqui aonde ?

**Comment by trupakufi** [comment]
@antonio-pedro99 Checa ainda a PR dessa Issiue.
