### ISSUE TITLE
feat: adicionar suporte para outros idiomas

### ISSUE THREAD

**Issue by antonio-pedro99** [angolaosc/aosc.social#8]
O site está em português, seria fixe se o mesmo estivesse disponível para inglês e Francês.

**Comment by Danguya** [comment]
**Mr.Aguinaldo**, vai dar um jeito nesta feat.

**Comment by mraguinaldo** [comment]
Farei isso pessoal.

**Comment by antonio-pedro99** [comment]
Que tal deixar a issue para o Hackathon? 
O @mraguinaldo é eligible a participar.

**Comment by Afranioalves** [comment]
777- team debuger está resolvendo essa Issue

**Comment by domingoscapolo** [comment]
@aoscode estou a trabalhar nisso

**Comment by domingoscapolo** [comment]
@aoscode estou a trabalhar nesse

**Comment by Danguya** [comment]
🎉 Issue Fechada - Suporte a Vários Idiomas 🎉

PR #50 

Todos os requisitos iniciais desta issue foram atendidos com sucesso, incluindo a implementação do suporte para inglês e português. Com isso, estou procedendo para fechar esta issue.

obrigado pela contribuição @Afranioalves
