### ISSUE TITLE
feat: adicionar tema dark mode

### ISSUE THREAD

**Issue by antonio-pedro99** [angolaosc/aosc.social#9]
Seria legal se o site tivesse o modo dark.

**Comment by Jacintomuambumba** [comment]
Vou trabalhar nisso então

**Comment by Nelson0Simao** [comment]
Adicionai uma funcionalidade de dark mode.

**Comment by Jacintomuambumba** [comment]
então já esta feito?

**Comment by antonio-pedro99** [comment]
> então já esta feito?

O @Nelson0Simao já está a trabalhar nesta issue

**Comment by Jacintomuambumba** [comment]
Certo

António Pedro ***@***.***> escreveu em qui., 12/10/2023 às
08:32 :

**Comment by Afranioalves** [comment]
777- team debuger está resolvendo essa Issue
